---
- hosts: all
  remote_user: root
  pre_tasks:
    - name: Install openshift_facts requirements
      yum:
        name: "{{ item }}"
      with_items:
        - python-yaml
        - python-ipaddress
    - name: Include openshift_facts module
      import_role:
        name: "{{ openshift_ansible_dir }}/roles/openshift_facts"
    - name: Load openshift facts
      openshift_facts:
        role: common
    - name: lololololololo
      debug:
        msg: "{{ docker_dev }}"
  roles:
    - "{{ playbook_dir }}/openshift/roles/prerequisites"
    - "openshift-contrib/roles/docker-storage-setup"
  post_tasks:
    - name: Enable and start docker service
      service:
        state: started
        enabled: yes
        name: docker

    - name: Set local registry fack
      set_fact:
        openshift_docker_insecure_registries: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['gateway'] }}:8585"

- hosts: localhost
  connection: local
  tasks:
    - name: Start local registry
      shell: |
        "{{ playbook_dir }}/setup-local-registry.sh" \
          --ip "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['gateway'] }}" \
          --port 8585 \
          -c "{{ playbook_dir }}/containers.txt"

- import_playbook: "{{ openshift_ansible_dir }}/playbooks/byo/config.yml"

- hosts: masters
  tasks:
    - name: Configure oc admin user for testing
      shell: |
        user_name="{{ admin_test_user_name | default('test_admin') }}"
        oc login -u system:admin
        oc get user "$user_name" || oc create user "$user_name"
        oc adm policy add-cluster-role-to-user cluster-admin "$user_name"
